update

diff --git a/.github/workflows/deploy-server.yml b/.github/workflows/deploy-server.yml
--- a/.github/workflows/deploy-server.yml
+++ b/.github/workflows/deploy-server.yml
@@ -5,14 +5,14 @@ on:
     secrets:
       SSH_KEY:
         required: true
-      SERVER_IP: 
+      SERVER_IP:
         required: true
 
 jobs:
   deploy:
     runs-on: ubuntu-latest
     steps:
-      - uses: actions/checkout@v3
+      - uses: actions/checkout@v4
       - name: Configure SSH
         run: |
           mkdir -p ~/.ssh/
@@ -32,4 +32,10 @@ jobs:
         run: ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.server.yml stop'
 
       - name: Start the server
-        run: ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.server.yml up --build'
+        run: |
+          ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.server.yml up --build'
+          exit_code=$?
+          if [ $exit_code -ne 0 ]; then
+            echo "docker-compose failed with exit code $exit_code"
+            exit $exit_code
+          fi
