update

diff --git a/.github/workflows/deploy-server.yml b/.github/workflows/deploy-server.yml
--- a/.github/workflows/deploy-server.yml
+++ b/.github/workflows/deploy-server.yml
@@ -32,4 +32,10 @@ jobs:
         run: ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.server.yml stop'
 
       - name: Start the server
-        run: ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.server.yml up --build --abort-on-container-exit --exit-code-from server'
+        run: |
+          ssh prod 'cd /home/mat/sgsg/ && docker compose -f docker-compose.server.yml up --build --abort-on-container-exit --exit-code-from server'
+          ssh_exit_code=$?
+          if [ $ssh_exit_code -eq 0 ]; then
+            echo "SSH command failed with exit code $ssh_exit_code"
+            exit $ssh_exit_code
+          fi
